```{r, message = FALSE}
#Data/Wrangling + Libraries
#Will create merged RDS file to load once for analysis
library(survey)
library(haven)
library(tidyverse)
library(knitr)

NHANES2013_14MEN <- read_xpt("Mental201314.xpt") #Mental 2013-2014
NHANES2015_16MEN <- read_xpt("Mental201516.xpt") #Mental 2015-2016
NHANES2017_20MEN <- read_xpt("Mental20172020.xpt") #Mental 2017-2020
NHANES2021_23MEN <- read_xpt("Mental202123.xpt") #Mental 2021-2023
NHANES2021_23FUN <- read_xpt("Function202123.xpt") #Function 2021-2023

MEN_MERGED_NHANES <- rbind(NHANES2013_14MEN,NHANES2015_16MEN,NHANES2017_20MEN,NHANES2021_23MEN) #rbind because variables are the same

saveRDS(MEN_MERGED_NHANES, "NHANES_MENTAL_MERGE.rds")
```

```{r}
#making data that will be loaded to an RDS, ignore this code block for future references 
#Remove 2021-2023 data
MEN_MERGED_NHANES2 <- MEN_MERGED_NHANES %>% filter(Survey_Cycle != "2021-2023")
readRDS("BP_NHANES.rds") #Sourced from BP_NHANES.Rmd
BP_NHANES$SEQN <- BP_NHANES$svy_id
BP_MERGE <- merge(BP_NHANES,MEN_MERGED_NHANES2, by = "SEQN")
saveRDS(BP_MERGE, "BP_MEN_MERGE.rds")
```